repos:
  - repo: local
    hooks:
      - id: eslint
        name: ESLint Code Quality Check
        entry: npx eslint --max-warnings=0
        language: system
        files: '\.(js|jsx|ts|tsx|html|css)$'
        pass_filenames: true
        always_run: true
