name: Deploy React App to cPanel

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Build React App
        run: CI=false npm run build

      - name: Deploy via SSH to cPanel
        uses: easingthemes/ssh-deploy@v5.0.1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.CPANEL_HOST }}
          REMOTE_USER: ${{ secrets.CPANEL_USER }}
          SOURCE: "build/"
          TARGET: ${{ secrets.CPANEL_PATH }}
          ARGS: "-avz --delete"
          SSH_ARGS: "-o IdentitiesOnly=yes -o StrictHostKeyChecking=no"
